### ISSUE TITLE
client.drives.by_drive_id().get() returns None-type "root" or "items"

### ISSUE THREAD

**Issue by suibinz** [microsoftgraph/msgraph-beta-sdk-python#138]
client_drive = await client.drives.by_drive_id("CLIENT_ID").get()
>>> client_drive.name
'OneDrive'
>>> client_drive.items
>>> client_drive.root
>>> type(client_drive.root)
<class 'NoneType'>
>>> type(client_drive.items)
<class 'NoneType'>

But Querying from Graph Explorer can return the right files.

**Comment by petrhollayms** [comment]
Hi @suibinz ,

Is the issue still there? If so, could you please share more information about the SDK version and the scenario? Sample code and error or result you are getting?
