### ISSUE TITLE
Wrong/confusing generation of properties (e.g IPv4 => i_pv4,)

### ISSUE THREAD

**Issue by haavardw** [microsoftgraph/msgraph-beta-sdk-python#181]
There's some rather confusing and annoying property names being generated. Even my github copilot gets this wrong.

Example: msgraph.generated.models.ti_indicator.TiIndicator has translated the field "networkIPv4" to the class property `network_i_pv4`. There's plenty of similar cases just in this class.

A better (IMO) translation would be `network_ip_v4` or `network_ipv4`.

**Comment by rkodev** [comment]
Hi @haavardw , thanks for Trying out the Graph Python SDK.  This issue is currently being addressed on the [Kiota repo ](https://github.com/microsoft/kiota/issues/4531), which is responsible for generation of this SDK. Please feel free to follow the conversation there for more information
