### ISSUE TITLE
Broken models having enum types

### ISSUE THREAD

**Issue by haavardw** [microsoftgraph/msgraph-beta-sdk-python#182]
It seems like all the Enum types are wrongly generated. All the values have a trailing comma (making it a tuple type), resulting in the values being serialized as lists, so all API calls fails.

Example msgraph.generated.models.ti_action:
```
from enum import Enum

class TiAction(Enum):
    Unknown = "unknown",
    Allow = "allow",
    Block = "block",
    Alert = "alert",
    UnknownFutureValue = "unknownFutureValue",
```
which as an examle the value TiAction.Alert ends up being serialized to json `{ ..., "action": ["alert"], ...}

Correct class should be
```
from enum import Enum

class TiAction(Enum):
    Unknown = "unknown"
    Allow = "allow"
    Block = "block"
    Alert = "alert"
    UnknownFutureValue = "unknownFutureValue"
```
which results in the correct serialization to json `{ ..., "action": "alert" }`

**Comment by haavardw** [comment]
Fixed with #186

**Comment by soilsquirrel** [comment]
@haavardw this doesnt seem to be fixed, neither in the version hosted on PyPI nor when i install directly from git.
see https://github.com/microsoftgraph/msgraph-beta-sdk-python/blob/main/msgraph/generated/models/ti_action.py

**Comment by haavardw** [comment]
@soilsquirrel yes, the fix is to subclass both str an enum. The serialization result is then a single string. That being said, I gave up on the beta-sdk and reverted to manually add typing on top of the native API instead. This project currently has too low quality and testing for my appetite..

**Comment by soilsquirrel** [comment]
nvm, for some weird reason installing the version from git didn't succeed. after testing out what you said, i checked my site-packages and there the subclassing of `str` was missing. did a clean reinstall from git, now it seems to work.

**Comment by haavardw** [comment]
@soilsquirrel I believe new releases are deployed without bumping the version number, so you have effectively no control over what code you will be running when you use the beta-sdk. We were happily running production code with this library for a few months when suddenly this serialization bug appeared, and now it seems to be fixed again, without any versioning changes. To me this was a show-stopper using this project. I cannot trust that what has previously passed testing, will continue to work..
