### ISSUE TITLE
pip package size

### ISSUE THREAD

**Issue by haavardw** [microsoftgraph/msgraph-beta-sdk-python#184]
The current unzipped pip package size is >600MB making it unusable for deployment on systems like e.g. AWS lambda in my case.

It would be good if e.g. the package could be organized like e.g. the aws boto3 library where the services needed are packaged as package "extras" so you can do something like this in requirements.txt:
```
msgraph-beta-sdk[security,me] == 1.0.0a9
```

**Comment by rkodev** [comment]
Hi @haavardw , Thanks for trying the Graph Python SDK. 
Currently, this SDK is generated using [kiota](https://github.com/microsoft/kiota) and the guidelines on how to generated the SDK is dependent on the Kiota library. If you are still interested in having this discussion, kindly open an issue/discussion in Kiota for better visibility and we can have this discussion on the repo. Please start by testing and sharing your experience with the latest version of the SDK
