### ISSUE TITLE
'GraphRequestAdapter' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by jaunt** [microsoftgraph/msgraph-beta-sdk-python#300]
We have been using version 1.0.0.a9 to upload policies to azure b2c without issue.  Upgrading to 1.0.0 throws the following error:

```
 File "<mylocalpaths>/site-packages/kiota_authentication_azure/azure_identity_access_token_provider.py", line 103, in get_authorization_token
    result = self._credentials.get_token(*self._scopes, claims=decoded_claim)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GraphRequestAdapter' object has no attribute 'get_token'
```

Any thoughts?

**Comment by iargue** [comment]
The values of GraphServiceClient has changed, so you'll need to update your query to include the specific parameter request_adapter=

Example:

Old config

`self.client = GraphServiceClient(self.adapter)`

New config

`self.client = GraphServiceClient(request_adapter=self.adapter)`
