### ISSUE TITLE
Exception: Invalid key: Google for enum <enum 'ManagementAgentType'>.

### ISSUE THREAD

**Issue by fa-tech-net** [microsoftgraph/msgraph-beta-sdk-python#320]
While fetching managed devices with the following call : 

_GraphServiceClient -> device_management.managed_devices.get()_

```
  File "[...]\msgraph_beta\generated\models\managed_device.py", line 400, in <lambda>
    "managementAgent": lambda n : setattr(self, 'management_agent', n.get_enum_value(ManagementAgentType)),
  File "[...]\kiota_serialization_json\json_parse_node.py", line 201, in get_enum_value
    raise Exception(f'Invalid key: {camel_case_key} for enum {enum_class}.')
Exception: Invalid key: Google for enum <enum 'ManagementAgentType'>.
```

File generated is missing a management agent type **google**, in class ManagementAgentType from **generated\models\management_agent_type.py**

Manually adding the Google enum in the file fix the issue

**Comment by SilasKenneth** [comment]
Hi @fa-tech-net , 
Sorry for the late response. 
Looks like this is an issue that was resolved in https://github.com/microsoftgraph/msgraph-beta-sdk-python/pull/316.
Kindly confirm if you are still facing the issue.

**Comment by fa-tech-net** [comment]
It solves the issue, thanks !
